### ISSUE TITLE
Add and implement a code style.

### ISSUE THREAD

**Issue by israelst** [raphamorim/waterfall.js#11]

**Comment by thiamsantos** [comment]
I think that today the best code styles are [xo](https://github.com/sindresorhus/xo) and [standard](http://standardjs.com/), personally I prefer xo ;)

I would like to send a PR but before sending it the following questions need to be answered to prevent bikeshedding:
- Semicolons? Yes or no?
- Indentation? Spaces? Tabs? 2 or 4?

**Comment by raphamorim** [comment]
I really like [Airbnb js-style](https://www.npmjs.com/package/eslint-config-airbnb) and [Standard](https://github.com/feross/standard)

**Comment by thiamsantos** [comment]
So I can send a PR adding [Standard](http://standardjs.com/) to the project?

**Comment by raphamorim** [comment]
Yup, and please add standart badge on README :)
