### ISSUE TITLE
Layout goes wrong with setting element style of parent.

### ISSUE THREAD

**Issue by JSoon** [raphamorim/waterfall.js#13]
@raphamorim 
Hey dude, sorry to call for your help, here is what happened:

I'm using waterfall.js, and I define my html like this:

```
<div class="waterfall">
  <div class="item">...</div>
  <div class="item">...</div>
  <div class="item">...</div>
</div>
```

And my styles like this:

```
<style>
* {
  box-sizing: border-box;
}
.waterfall {
  margin-left: -15px;
  margin-right: -15px;
}
.item {
  width: 25%;
  padding-left: 15px;
  padding-right: 15px;
}
</style>
```

OK, let's see...hmmm...WOW!

![waterfall](https://cloud.githubusercontent.com/assets/7589350/11978743/d4cbb4d8-a9c8-11e5-9d1f-322d4aae16cc.jpg)

See, strange things happened, right? The 4th column comes out in the wrong position.

BTW, this issue appears in Chrome and Firefox, and Safari is just fine.

<hr>

Edit issue again. Now I find another problem:

This time i change my styles( and I thought this may not be the primary reason ):

```
<style>
* {
  box-sizing: border-box;
}
.waterfall {
}
.item {
  width: 25%;
}
</style>
```

When i close the dev tools in Chrome( means page cache is enabled ), when i click the refresh button, page just shows up like this, which is happened in a random probability.

![waterfall2](https://cloud.githubusercontent.com/assets/7589350/11979517/f588e654-a9ce-11e5-850d-513f821944a4.jpg)

**Comment by raphamorim** [comment]
Whoa, sorry by delay. I'm traveling, but I'll see this issue in this weekend.
Can you help too @israelst ?

**Comment by JSoon** [comment]
I just figure out the 2nd mess, and I'm sure it's because the images in the waterfall haven't been loaded before waterfall.js calculate the height of them.
And haha, I think maybe it's time to break "1kb" then? :laughing:

**Comment by raphamorim** [comment]
Hmmm.... I've create another minimalist lib to solve this problem too. https://github.com/raphamorim/imgStatus

**Comment by raphamorim** [comment]
I had the same problem and the data were heavy.Then I created to trigger the waterfall when the images were loaded.

**Comment by JSoon** [comment]
Got it. Hope to provide a link for [waterfall](http://raphamorim.com/waterfall.js/) to jump to [imgStatus](http://raphamorim.com/imgStatus/).

**Comment by raphamorim** [comment]
Yeah, I'll add it on a toDo issue.
Related: #14
