### ISSUE TITLE
require by commonJS

### ISSUE THREAD

**Issue by lucasmaiaesilva** [raphamorim/waterfall.js#15]
I've been installed the waterfall.js and require the lib to be compiled by browserify, but when I run the command the browserify returns an error, I think this is happening because of the name with the extension ".js", because of this, the browserify recognizes this module as a local file in project. And returns a not found error.

**Comment by rafaelcorreiapoli** [comment]
Happening to me too

**Comment by raphamorim** [comment]
Solved in 1.1.0 (10f398b4b2c0caeca6629824092ade143ad038bc)

Thanks for reporting :)
