### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by igidas** [raphamorim/waterfall.js#17]
Hey,

Just tested this awesome land lightweight script with my site and found some issues.
Here is a test case: https://jsfiddle.net/ucgvpjp0/2/

1. If using borders for gutters instead of paddings, Waterfall calculates layout incorrectly. 
2. Items width is set to 33.33%, but resizing window makes grid items to jump on some points. Maybe something with subpixel rounding?
3. Then there are more then one element with same class and Waterfall is called using that class, layout is calculated only on the first one.

**Comment by raphamorim** [comment]
Sorry by delay.
I'll see this issue in this week.

**Comment by igidas** [comment]
Hey, any updates? Planning to use this script in another project.

**Comment by israelst** [comment]
@igidas #20 solves 1) and 2). Your third point isn't actually a bug, your are selecting the first element using that class again. 

@raphamorim, this ( 3) ) is one of the reasons to not support query strings as input. it will be great to discuss it again to a following version.

**Comment by raphamorim** [comment]
LGTM @israelst, I'll open another issue to discuss this point. 

Thank you @igidas for your time :)
