### ISSUE TITLE
Get the number of elements in the grid

### ISSUE THREAD

**Issue by lnmunhoz** [raphamorim/waterfall.js#24]
It is possible? Like masonry has the 'onLayoutComplete' callback. I need something like that to retrieve the number of items that was adjusted by waterfall.

**Comment by raphamorim** [comment]
Yeah, it's possible.
But does make sense make this change?

In which cases you think it gonna be useful @lnmunhoz?
What do you think @israelst ?

**Comment by lnmunhoz** [comment]
I'm using in a infinite loading context. I just solved like this: 

```js
const cardsBox = this.firstNode;
  cardsBox._uihooks = {
    insertElement: (node, next) => {
      $(node).insertBefore(next);
      $(node).imagesLoaded(() => {
        // Retrieve the current amount on the grid
        this.data.onItemReady($('.grid').find('.item').length);
        waterfall('.grid')
      }); 
    }
```
After each rendered item I'm getting the length of the grid and passing to my `onItemReady` callback. So when I reach a certain number of elements It will be able to "fetch more" in my list.

This is not actually a problem, I solved very quickly. But with masonry I had a callback that does this trick for me.

**Comment by israelst** [comment]
Hello @lnmunhoz, why don't you simply use `cardsBox.childNodes.length` or `cardsBox.childElementCount`?

Did I get something wrong?

> The Node.childNodes read-only property returns a live collection of child nodes of the given element.
https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes

**Comment by lnmunhoz** [comment]
Works perfectly!

**Comment by raphamorim** [comment]
Nice! 
I'll close this then 👍 

And document for this for future issues :)
