### ISSUE TITLE
Implements Tests

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/waterfall.js#3]

**Comment by pedropolisenso** [comment]
can any tool? @raphamorim

**Comment by raphamorim** [comment]
I prefer mocha/jasmine/nightwatch options, but since it use phantomjs. I'll agree w/ implementation :)

**Comment by pedropolisenso** [comment]
Ok, no problem. I'll use mocha or jasmine

2016-02-19 11:09 GMT-02:00 Raphael Amorim <notifications@github.com>:

> I prefer mocha/jasmine/nightwatch options, but since it use phantomjs.
> I'll agree w/ implementation :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raphamorim/waterfall.js/issues/3#issuecomment-186206622>
> .
>



-- 
Atenciosamente,

*Pedro Polisenso*
Front-end Developer at Prefeitura do Rio de Janeiro
Moderador do Front-end Carioca - 2015

*website: *www.pedropolisenso.com
*twitter: *twitter.com/pedropolisenso
*Linkedin:* linkedin.com/in/pedropolisenso

**Comment by raphamorim** [comment]
If you need/want references. I recommend follow the standart/format from  [Origami.js](http://github.com/raphamorim/origami.js) current tests.

**Comment by pedropolisenso** [comment]
Thank you for references, Raphael

**Comment by israelst** [comment]
@pedropolisenso, the step taken at #21 may help you to write unit tests.
