### ISSUE TITLE
How about support module style?

### ISSUE THREAD

**Issue by sculove** [raphamorim/waterfall.js#30]
I want to use waterfall.js
but I must use `waterfall` global function.

How about support moulde like AMD or UMD or es6 styles?

If you are busy, I am willing to contribute this issue.

**Comment by sculove** [comment]
a like issue #7

**Comment by raphamorim** [comment]
Solved in 1.1.0 (10f398b4b2c0caeca6629824092ade143ad038bc)

**Comment by sergiokopplin** [comment]
@raphamorim, i'm not able to use modules way in my project, is that really solved? how to use this way?

**Comment by sergiokopplin** [comment]
@raphamorim, this worked for me:

```
import waterfall from 'waterfall.js/src/waterfall';
```

you should add this on documentation :)

**Comment by raphamorim** [comment]
Nice @sergiokopplin,
Can you send a PR with this change in README.md?

**Comment by sergiokopplin** [comment]
sorry, to late. rs

here it doesn't work just with `from waterfall`, it must have the `waterfall.js/src/waterfall`.

Have you fixed that?

**Comment by raphamorim** [comment]
Updated, thanks :)
