### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by thiamsantos** [raphamorim/waterfall.js#33]
Would be cool to refactor the code to ES6, and provide the module through:
```js
// ES6 Modules
import waterfall from 'waterfall.js'

// CommonJS Modules
const waterfall = require('waterfall.js')
```
And a UMD version through [unpkg](https://unpkg.com/).

Maybe also take that opportunity  to refactor and implement the tests #3.

What do you think about that?

**Comment by raphamorim** [comment]
Today, the code already works to ES6 imports and UMD

**Comment by raphamorim** [comment]
https://github.com/raphamorim/waterfall.js/blob/master/src/waterfall.js#L13

**Comment by raphamorim** [comment]
A good approach is improve ES6 import, to change `import waterfall from 'waterfall'`

**Comment by thiamsantos** [comment]
> Today, the code already works to ES6 imports and UMD

I was thinking in rewrite the lib using ES6 syntax and the import/export statement, and use a module bundler like [rollup](http://rollupjs.org/) to compile to a commonjs version and a UMD version. And expose the three.

> A good approach is improve ES6 import, to change import waterfall from 'waterfall'

The problem is that [there is already a package under the name waterfall](https://www.npmjs.com/package/waterfall). And the current name seems to be a bit trick [waterfall.js](https://www.npmjs.com/package/waterfall.js) looks like I am importing a file not a module. The npm also [recommends to not use js in the name of the package](https://docs.npmjs.com/files/package.json#name).
