### ISSUE TITLE
Columns are stacked to the left

### ISSUE THREAD

**Issue by felquis** [raphamorim/waterfall.js#41]
Follow the print

![image](https://user-images.githubusercontent.com/736728/31052165-873ed35c-a652-11e7-9520-c34a85bf4f86.png)

Is it possible to make them feel more balanced with the right side of the screen?

**Comment by raphamorim** [comment]
The latest stable is waterfall-1.0.2

**Comment by raphamorim** [comment]
Can you try with this one?
Ref #37

**Comment by felquis** [comment]
Olha o bicho limpando a casa.
