### ISSUE TITLE
not `bower install waterfall.js` but `bower install waterfal`

### ISSUE THREAD

**Issue by Leginion** [raphamorim/waterfall.js#43]
```
D:\foo>bower install waterfall.js
bower                        ENOTFOUND Package waterfall.js not found

D:\foo>bower install waterfalljs
bower                        ENOTFOUND Package waterfalljs not found

D:\foo>bower install waterfall
bower waterfall#*           not-cached https://github.com/raphamorim/waterfall.js.git#*
bower waterfall#*              resolve https://github.com/raphamorim/waterfall.js.git#*
bower waterfall#*             download https://github.com/raphamorim/waterfall.js/archive/v1.1.0.tar.gz
```

Maybe you need update the document at "http://raphamorim.io/waterfall.js/" -> "How to get this?"

**Comment by raphamorim** [comment]
oh thanks by the heads up! 
@LazyKnightX  can you send a PR to fix that?

**Comment by Leginion** [comment]
@raphamorim glad to see this repo is still in maintaining.
Yet but I didn't find the repo refer to link "http://raphamorim.io/waterfall.js/". (even in your blog repo)
I'm glad to help, but I need tiny help here, thank you.

**Comment by raphamorim** [comment]
Thanks @LazyKnightX for the issue. I have updated in the website 🥇
